In [ ]:
# converting csv fil to parquet fomate

#------------------------------------------------
import pandas as pd

df = pd.read_csv("fashionnova.csv")

df

,Breadcrumbs,Product Name,Selling Price,Regular Price,Discount Percentage,Color,Sizes Available,Product URL,data_source_url
0,Women › New Arrivals,Mila Stretch Capri Denim Jeans - Vintage Wash,$14.99,$24.99,40% OFF,"Dark Wash, Vintage Wash","1, 3, 5, 7, 9, 11, 13",https://www.fashionnova.com/products/mila-stre...,https://www.fashionnova.com/collections/new?pa...
1,Women › New Arrivals,Devon Ruched Drawstring Mock Neck Top - Butter...,$13.49,$22.99,40% OFF,ButterYellow,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/devon-ruc...,https://www.fashionnova.com/collections/new?pa...
2,Women › New Arrivals,Mickey Mouse And Pluto Drop Shoulder Tee - White,$11.99,$19.99,40% OFF,White,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/mickey-mo...,https://www.fashionnova.com/collections/new?pa...
3,Women › New Arrivals,Amelia Striped Maxi Dress - Brown/combo,$20.99,$34.99,40% OFF,Brown/combo,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/amelia-st...,https://www.fashionnova.com/collections/new?pa...
4,Women › New Arrivals,Day Out Smocked Gingham Chiffon Top - Black/White,$16.49,$27.99,40% OFF,Black/White,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/day-out-s...,https://www.fashionnova.com/collections/new?pa...
...,...,...,...,...,...,...,...,...,...
111,Women New Arrivals,Prime Care Belted Uniform Scrub Jumpsuit - Black,$20.99,$34.99,40% Off,Black,"S, M, L, XL, 2X",https://www.fashionnova.com/products/prime-car...,https://www.fashionnova.com/collections/new?pa...
112,Women New Arrivals,Ocean Views Foldover Striped Linen Top - Blue/...,$20.99,$34.99,40% Off,Blue/combo,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/ocean-vie...,https://www.fashionnova.com/collections/new?pa...
113,Women New Arrivals,Serenity Sculpted Seamless Bodysuit - Cream,$11.99,$19.99,40% Off,Cream,"S/M, M/L, 1X/2X, 2X/3X",https://www.fashionnova.com/products/serenity-...,https://www.fashionnova.com/collections/new?pa...
114,Women New Arrivals,Natalia Striped Maxi Dress - Kelly Green,$17.99,$29.99,40% Off,Kelly Green,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/natalia-s...,https://www.fashionnova.com/collections/new?pa...
115,Women New Arrivals,Second Skin Double Lined Lace Trim Cami Top - ...,$11.99,$19.99,40% Off,Black,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/second-sk...,https://www.fashionnova.com/collections/new?pa...

In [3]:
df.to_parquet("fashionnova.parquet", engine="pyarrow")

In [8]:
df2 = pd.read_parquet("fashionnova.parquet", engine="pyarrow")

In [9]:
df2

,Breadcrumbs,Product Name,Selling Price,Regular Price,Discount Percentage,Color,Sizes Available,Product URL,data_source_url
0,Women › New Arrivals,Mila Stretch Capri Denim Jeans - Vintage Wash,$14.99,$24.99,40% OFF,"Dark Wash, Vintage Wash","1, 3, 5, 7, 9, 11, 13",https://www.fashionnova.com/products/mila-stre...,https://www.fashionnova.com/collections/new?pa...
1,Women › New Arrivals,Devon Ruched Drawstring Mock Neck Top - Butter...,$13.49,$22.99,40% OFF,ButterYellow,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/devon-ruc...,https://www.fashionnova.com/collections/new?pa...
2,Women › New Arrivals,Mickey Mouse And Pluto Drop Shoulder Tee - White,$11.99,$19.99,40% OFF,White,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/mickey-mo...,https://www.fashionnova.com/collections/new?pa...
3,Women › New Arrivals,Amelia Striped Maxi Dress - Brown/combo,$20.99,$34.99,40% OFF,Brown/combo,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/amelia-st...,https://www.fashionnova.com/collections/new?pa...
4,Women › New Arrivals,Day Out Smocked Gingham Chiffon Top - Black/White,$16.49,$27.99,40% OFF,Black/White,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/day-out-s...,https://www.fashionnova.com/collections/new?pa...
...,...,...,...,...,...,...,...,...,...
111,Women New Arrivals,Prime Care Belted Uniform Scrub Jumpsuit - Black,$20.99,$34.99,40% Off,Black,"S, M, L, XL, 2X",https://www.fashionnova.com/products/prime-car...,https://www.fashionnova.com/collections/new?pa...
112,Women New Arrivals,Ocean Views Foldover Striped Linen Top - Blue/...,$20.99,$34.99,40% Off,Blue/combo,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/ocean-vie...,https://www.fashionnova.com/collections/new?pa...
113,Women New Arrivals,Serenity Sculpted Seamless Bodysuit - Cream,$11.99,$19.99,40% Off,Cream,"S/M, M/L, 1X/2X, 2X/3X",https://www.fashionnova.com/products/serenity-...,https://www.fashionnova.com/collections/new?pa...
114,Women New Arrivals,Natalia Striped Maxi Dress - Kelly Green,$17.99,$29.99,40% Off,Kelly Green,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/natalia-s...,https://www.fashionnova.com/collections/new?pa...
115,Women New Arrivals,Second Skin Double Lined Lace Trim Cami Top - ...,$11.99,$19.99,40% Off,Black,"XS, S, M, L, XL, 1X, 2X, 3X",https://www.fashionnova.com/products/second-sk...,https://www.fashionnova.com/collections/new?pa...

In [ ]:
# converting parquet fomate to csv file

In [10]:



df.to_csv("fashionnov_parquettocsv.csv", index=False)

------------------------------------------------------------------------------------------------------------------------------------------------

json to parquet
------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [12]:
jsondf = pd.read_json("users.json")

jsondf

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [15]:
json_to_parquet  = jsondf.to_parquet("users.parquet", engine="pyarrow", index= False)

json_to_parquet

p_jdf = pd.read_parquet("users.parquet", engine="pyarrow")

p_jdf

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [16]:
# converting parquet to json file
p_jdf.to_json("users_parquet_to_json", orient="records", indent=4)

<!--  orient="records"

This controls the structure of the JSON.

Suppose your DataFrame is:

Name	Age
John	25
Sara	30

With:

orient="records"

Output:

[
  {
    "Name": "John",
    "Age": 25
  },
  {
    "Name": "Sara",
    "Age": 30
  }
] -->

<!-- Each row becomes a JSON object (record).

Without orient="records" (default):

{
  "Name":{"0":"John","1":"Sara"},
  "Age":{"0":25,"1":30}
} -->

<!-- indent=4

This makes the JSON readable by adding spaces and line breaks -->

---------------------------------------------------------------------------------------------
csv to xlsx
and 

xlsx to paquet

In [17]:
df = pd.read_csv("fashionnov_parquettocsv.csv")

# Save as Excel file
df.to_excel("data.xlsx", index=False)

print("CSV converted to XLSX successfully!")

CSV converted to XLSX successfully!

In [18]:
df.to_parquet("data.parquet", engine="pyarrow", index=False)

In [22]:
xsd = pd.read_parquet("data.parquet", engine="pyarrow")

xsd.to_csv("data.csv", index= False)