In [13]:
import pandas as pd
df = pd.read_parquet("swiggy_instamart_2026_06_16.parquet")



df

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,...,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,JJPBU6882K,9MWP13YQKE,NaN,"Atta, Rice and Dal",...,Yes,No,35,NaN,No offer,35,0,8,https://www.swiggy.com/instamart/item/9MWP13YQKE,https://instamart-media-assets.swiggy.com/swig...
1,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,DIQNWDNUNH,BI8M5ZXAW9,NaN,"Atta, Rice and Dal",...,Yes,Yes,75,NaN,49% OFF,75,49,1,https://www.swiggy.com/instamart/item/BI8M5ZXAW9,https://instamart-media-assets.swiggy.com/swig...
2,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,K79TNFTLWJ,X9SQLG6CTE,NaN,"Atta, Rice and Dal",...,Yes,Yes,95,NaN,5% OFF,95,5,1,https://www.swiggy.com/instamart/item/X9SQLG6CTE,https://instamart-media-assets.swiggy.com/swig...
3,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,RK5XDYXJIX,LHNJ100V83,NaN,"Atta, Rice and Dal",...,Yes,Yes,117,NaN,21% OFF,117,21,1,https://www.swiggy.com/instamart/item/LHNJ100V83,https://instamart-media-assets.swiggy.com/swig...
4,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,6CJ1V31SSP,7E2FXNPLM2,NaN,"Atta, Rice and Dal",...,Yes,Yes,85,NaN,42% OFF,85,42,1,https://www.swiggy.com/instamart/item/7E2FXNPLM2,https://instamart-media-assets.swiggy.com/swig...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11757,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,WGWQM4AMDS,37NDDNLP4B,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,1027,NaN,14% OFF,1027,14,3,https://www.swiggy.com/instamart/item/37NDDNLP4B,https://instamart-media-assets.swiggy.com/swig...
11758,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,ZQL5HK6GQ5,FNG1JF7ZJ1,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,501,NaN,14% OFF,501,14,1,https://www.swiggy.com/instamart/item/FNG1JF7ZJ1,https://instamart-media-assets.swiggy.com/swig...
11759,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,MSFOKAOGB9,SLI5TVYK9G,NaN,Ice Creams and Frozen Desserts,...,No,Yes,259,NaN,3% OFF,259,3,0,https://www.swiggy.com/instamart/item/SLI5TVYK9G,https://instamart-media-assets.swiggy.com/swig...
11760,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,PDA0H1H01I,WQDN32S96X,NaN,Ice Creams and Frozen Desserts,...,No,Yes,237,NaN,5% OFF,237,5,0,https://www.swiggy.com/instamart/item/WQDN32S96X,https://instamart-media-assets.swiggy.com/swig...
11761,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,1ZQBTYBPPC,757P4WZBXZ,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,249,NaN,15% OFF,249,15,3,https://www.swiggy.com/instamart/item/757P4WZBXZ,https://instamart-media-assets.swiggy.com/swig...

In [ ]:
# converting the file into csv

converting_to_csv =df.to_csv("swiggy_instamart_2026_06_16.csv", index= False)

In [ ]:
pd.read_csv("swiggy_instamart_2026_06_16.csv")

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,...,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,JJPBU6882K,9MWP13YQKE,NaN,"Atta, Rice and Dal",...,Yes,No,35,NaN,No offer,35,0,8,https://www.swiggy.com/instamart/item/9MWP13YQKE,https://instamart-media-assets.swiggy.com/swig...
1,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,DIQNWDNUNH,BI8M5ZXAW9,NaN,"Atta, Rice and Dal",...,Yes,Yes,75,NaN,49% OFF,75,49,1,https://www.swiggy.com/instamart/item/BI8M5ZXAW9,https://instamart-media-assets.swiggy.com/swig...
2,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,K79TNFTLWJ,X9SQLG6CTE,NaN,"Atta, Rice and Dal",...,Yes,Yes,95,NaN,5% OFF,95,5,1,https://www.swiggy.com/instamart/item/X9SQLG6CTE,https://instamart-media-assets.swiggy.com/swig...
3,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,RK5XDYXJIX,LHNJ100V83,NaN,"Atta, Rice and Dal",...,Yes,Yes,117,NaN,21% OFF,117,21,1,https://www.swiggy.com/instamart/item/LHNJ100V83,https://instamart-media-assets.swiggy.com/swig...
4,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,6CJ1V31SSP,7E2FXNPLM2,NaN,"Atta, Rice and Dal",...,Yes,Yes,85,NaN,42% OFF,85,42,1,https://www.swiggy.com/instamart/item/7E2FXNPLM2,https://instamart-media-assets.swiggy.com/swig...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11757,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,WGWQM4AMDS,37NDDNLP4B,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,1027,NaN,14% OFF,1027,14,3,https://www.swiggy.com/instamart/item/37NDDNLP4B,https://instamart-media-assets.swiggy.com/swig...
11758,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,ZQL5HK6GQ5,FNG1JF7ZJ1,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,501,NaN,14% OFF,501,14,1,https://www.swiggy.com/instamart/item/FNG1JF7ZJ1,https://instamart-media-assets.swiggy.com/swig...
11759,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,MSFOKAOGB9,SLI5TVYK9G,NaN,Ice Creams and Frozen Desserts,...,No,Yes,259,NaN,3% OFF,259,3,0,https://www.swiggy.com/instamart/item/SLI5TVYK9G,https://instamart-media-assets.swiggy.com/swig...
11760,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,PDA0H1H01I,WQDN32S96X,NaN,Ice Creams and Frozen Desserts,...,No,Yes,237,NaN,5% OFF,237,5,0,https://www.swiggy.com/instamart/item/WQDN32S96X,https://instamart-media-assets.swiggy.com/swig...
11761,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,1ZQBTYBPPC,757P4WZBXZ,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,249,NaN,15% OFF,249,15,3,https://www.swiggy.com/instamart/item/757P4WZBXZ,https://instamart-media-assets.swiggy.com/swig...

In [ ]:
# converting into jason file the parquet format


converting_to_json = df.to_json("swiggy_instamart_2026_06_16.json", orient="records", indent =4)

In [ ]:
pd.read_json("swiggy_instamart_2026_06_16.json")

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,...,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,JJPBU6882K,9MWP13YQKE,NaN,"Atta, Rice and Dal",...,Yes,No,35,NaN,No offer,35,0,8,https://www.swiggy.com/instamart/item/9MWP13YQKE,https://instamart-media-assets.swiggy.com/swig...
1,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,DIQNWDNUNH,BI8M5ZXAW9,NaN,"Atta, Rice and Dal",...,Yes,Yes,75,NaN,49% OFF,75,49,1,https://www.swiggy.com/instamart/item/BI8M5ZXAW9,https://instamart-media-assets.swiggy.com/swig...
2,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,K79TNFTLWJ,X9SQLG6CTE,NaN,"Atta, Rice and Dal",...,Yes,Yes,95,NaN,5% OFF,95,5,1,https://www.swiggy.com/instamart/item/X9SQLG6CTE,https://instamart-media-assets.swiggy.com/swig...
3,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,RK5XDYXJIX,LHNJ100V83,NaN,"Atta, Rice and Dal",...,Yes,Yes,117,NaN,21% OFF,117,21,1,https://www.swiggy.com/instamart/item/LHNJ100V83,https://instamart-media-assets.swiggy.com/swig...
4,2026-06-13 13:13:16,swiggy instamart,1386719,NaN,NaN,110006,6CJ1V31SSP,7E2FXNPLM2,NaN,"Atta, Rice and Dal",...,Yes,Yes,85,NaN,42% OFF,85,42,1,https://www.swiggy.com/instamart/item/7E2FXNPLM2,https://instamart-media-assets.swiggy.com/swig...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11757,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,WGWQM4AMDS,37NDDNLP4B,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,1027,NaN,14% OFF,1027,14,3,https://www.swiggy.com/instamart/item/37NDDNLP4B,https://instamart-media-assets.swiggy.com/swig...
11758,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,ZQL5HK6GQ5,FNG1JF7ZJ1,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,501,NaN,14% OFF,501,14,1,https://www.swiggy.com/instamart/item/FNG1JF7ZJ1,https://instamart-media-assets.swiggy.com/swig...
11759,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,MSFOKAOGB9,SLI5TVYK9G,NaN,Ice Creams and Frozen Desserts,...,No,Yes,259,NaN,3% OFF,259,3,0,https://www.swiggy.com/instamart/item/SLI5TVYK9G,https://instamart-media-assets.swiggy.com/swig...
11760,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,PDA0H1H01I,WQDN32S96X,NaN,Ice Creams and Frozen Desserts,...,No,Yes,237,NaN,5% OFF,237,5,0,https://www.swiggy.com/instamart/item/WQDN32S96X,https://instamart-media-assets.swiggy.com/swig...
11761,2026-06-13 13:27:46,swiggy instamart,1386719,NaN,NaN,110006,1ZQBTYBPPC,757P4WZBXZ,NaN,Ice Creams and Frozen Desserts,...,Yes,Yes,249,NaN,15% OFF,249,15,3,https://www.swiggy.com/instamart/item/757P4WZBXZ,https://instamart-media-assets.swiggy.com/swig...

In [ ]:
import os
os.system("java -version")